### basic ###
io_config: io.yaml
random_seed: 1024
gpu_id: "1"
### data ###
camnames: ['Camera1', 'Camera2', 'Camera3', 'Camera4', 'Camera5', 'Camera6','Camera7','Camera8','Camera9']
n_instances: 1
n_channels_out: 1
crop_height: [8, 712]
crop_width: [0, 1280]
downfac: 4

### training options ###
train_mode: new
com_finetune_weights: #./COM/weights/
num_validation_per_exp: 10
# NOTICE: actual batch size = batch_size*{num_cameras} 
batch_size: 2
epochs: 10
lr: 5e-5
loss:
    MSELoss:
      loss_weight: 1.0
metric: []
save_period: 5

# If true, saves plots of the training labels overlaid on images
#debug: True

# If present, write the confidence map output and image/COM overlays to disk during prediction
#com_debug: Camera5

### prediction ###
max_num_samples: max
